services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: doc_mind_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docmind
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/app/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: doc_mind_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/docmind
      OLLAMA_BASE_URL: http://docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8100:8100"
    volumes:
      - ./backend/app:/app/app
      - uploaded_files:/app/uploads
      
      # ⬇️ ADD THESE TWO MOUNTS TO BRING ALEMBIC INSIDE DOCKER ⬇️
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/alembic:/app/alembic
    command: uvicorn app.main:app --host 0.0.0.0 --port 8100 --reload

volumes:
  pgdata:
  uploaded_files:
